 
 create database FACULTAD_LAB;
 use FACULTAD_LAB;

CREATE TABLE FACULTAD(
	ID INT PRIMARY KEY,
	NOMBRE_F VARCHAR(40) NOT NULL,
	TELF CHAR(18) NOT NULL,
	TELF_FIJO CHAR(7),
	DIRECCION VARCHAR(20) NOT NULL,
	CORREO VARCHAR(50) NOT NULL,
)

CREATE TABLE PERSONAL(
	ID INT PRIMARY KEY IDENTITY,
	NOMBRE VARCHAR(40) NOT NULL,
	AP_PAT VARCHAR(25),
	AP_MAT VARCHAR(35),
	CI VARCHAR(11) NOT NULL,
	TELF CHAR(7),
	CELULAR CHAR(8) UNIQUE,
	DIREC VARCHAR(50) NOT NULL,
	NIT CHAR(11) UNIQUE,
	FECHA_NAC DATE,
	PROFESION VARCHAR(25) NOT NULL,
	GENERO CHAR(1) NOT NULL,
	ESTADO BIT NOT NULL
)

CREATE TABLE CONTRATO(
	ID INT PRIMARY KEY NOT NULL,
	ID_P INT NOT NULL,
	ID_P_CONTRATA INT NOT NULL,
	FECHA_INICIO DATE NOT NULL,
	FECHA_FIN DATE,
	FECHA DATETIME,
	ARCHIVO VARCHAR(60),
	FOREIGN KEY (ID_P) REFERENCES PERSONAL(ID),
	FOREIGN KEY (ID_P_CONTRATA) REFERENCES PERSONAL(ID)
)
CREATE TABLE TIPO_CONTRATO(
	ID INT PRIMARY KEY NOT NULL,
	NOMBRE_TIPO VARCHAR(40) NOT NULL,
	ID_CONTRATO INT,
	FECHA_INICIO DATE NOT NULL,
	FECHA_FIN DATE,
	HORA_INICIO TIME NOT NULL,
	HORA_FIN TIME NOT NULL,
	TURNO VARCHAR(20) NOT NULL,
	
	FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO(ID)
)
ALTER TABLE CONTRATO ADD SUELDO FLOAT
SELECT * FROM CONTRATO




CREATE TABLE ROL(
	ID INT PRIMARY KEY NOT NULL,
	ID_CONTRATO INT NOT NULL,
	NOMBRE_ROL VARCHAR(40),
	DESCRIPCION VARCHAR(60),
	FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO(ID)
)
CREATE TABLE CARRERA(
	ID INT PRIMARY KEY NOT NULL,
	NOMBRE_CARRERA VARCHAR(20),
	ID_FACULTAD INT NOT NULL, 
	CANTIDAD_ESTUDIANTES INT NOT NULL,
	TELF CHAR(8)NOT NULL,
	DIRECCION VARCHAR(20) NOT NULL,
	TIPO_CARRERA VARCHAR(20) NOT NULL,
	FOREIGN KEY (ID_FACULTAD) REFERENCES FACULTAD(ID)
)
CREATE TABLE MATRICULA(
	RU INT PRIMARY KEY,
	ID_P_MATRICULA INT NOT NULL,
	FECHA_MATRICULACION DATETIME NOT NULL,
	CLAVE VARCHAR(128) NOT NULL,
	GESTION CHAR(4) NOT NULL,
	ID_CARRERA INT NOT NULL,
	[NOMBRE DE LA CARRERA] VARCHAR(25),
	FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
)
CREATE TABLE ESTUDIANTE(
	ID INT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL, 
	AP_P_E VARCHAR(20),
	AP_M_E VARCHAR(20),
	FECHA_NAC DATE NOT NULL,
	CI CHAR(9) UNIQUE NOT NULL,
	CELULAR CHAR(8) NOT NULL,
	GENERO CHAR(1) CHECK(GENERO IN('M' , 'V')),
	RU INT UNIQUE NOT NULL,
	FOREIGN KEY (RU) REFERENCES MATRICULA(RU)
)
CREATE TABLE MATERIA(
	ID INT PRIMARY KEY,
	ID_CARRERA INT,
	NOMBRE_MATERIA VARCHAR(30) NOT NULL,
	GRUPO CHAR(1) NOT NULL,
	SIGLA CHAR(7) NOT NULL,
	FOREIGN KEY(ID_CARRERA) REFERENCES CARRERA(ID)
)
ALTER TABLE MATERIA ADD DESCRIPCION VARCHAR(30)

CREATE TABLE CURSAN(
	ID INT PRIMARY KEY, 
	ID_CLASES INT NOT NULL,
	RU INT UNIQUE NOT NULL,
	FOREIGN KEY (RU) REFERENCES ESTUDIANTE(RU),
	FOREIGN KEY (ID_CLASES) REFERENCES CARRERA(ID)

)

CREATE TABLE PROGRAMAR_MAT(
	ID INT PRIMARY KEY NOT NULL,
	ID_MATERIA INT NOT NULL,
	RU_ESTUDIANTE INT NOT NULL,
	FECHA_PROG DATE NOT NULL,
	FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID),
	FOREIGN KEY (RU_ESTUDIANTE) REFERENCES ESTUDIANTE(RU)
)
CREATE TABLE PROPIEDAD_FAC(
	ID INT PRIMARY KEY NOT NULL,
	m2 FLOAT NOT NULL,
	DIRECCION VARCHAR(40),
	ID_FACULTAD INT NOT NULL,
	FOREIGN KEY (ID_FACULTAD) REFERENCES FACULTAD(ID)
)

CREATE TABLE AMBIENTE_LAB(
	ID INT PRIMARY KEY NOT NULL,
	ID_PROPIEDAD INT NOT NULL,
	ID_P_ADMIN INT NOT NULL,
	PLANTA CHAR(1) NOT NULL,
	NUM_AMB CHAR(2) NOT NULL,
	CAPACIDAD INT NOT NULL,
	ESTADO BIT,
	FOREIGN KEY (ID_PROPIEDAD) REFERENCES PROPIEDAD_FAC(ID),
	FOREIGN KEY (ID_P_ADMIN) REFERENCES PERSONAL(ID)
)



CREATE TABLE REGISTRAR_AMB_LAB(
	ID INT PRIMARY KEY NOT NULL,
	ID_CARRERA INT NOT NULL,
	ID_AMB_LABORATORIO INT NOT NULL,
	FECHA_REG_LAB DATE,
	ID_PERSONAL_REGISTRA_LAB INT NOT NULL,
	OBSERVACIONES VARCHAR(25),
	FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID),
	FOREIGN KEY (ID_AMB_LABORATORIO) REFERENCES AMBIENTE_LAB(ID),
	FOREIGN KEY (ID_PERSONAL_REGISTRA_LAB) REFERENCES PERSONAL(ID)
)

CREATE TABLE USO_LAB(
	ID INT PRIMARY KEY NOT NULL,
	RU_ESTUDIANTE INT UNIQUE NOT NULL,
	ID_AMBIENTE INT NOT NULL,
	MOTIVO_SOLICITUD VARCHAR(15),
	FECHA DATE,
	ID_PERSONAL_A INT NOT NULL,
	FOREIGN KEY (RU_ESTUDIANTE) REFERENCES ESTUDIANTE(RU),
	FOREIGN KEY (ID_PERSONAL_A) REFERENCES PERSONAL(ID),
	FOREIGN KEY (ID_AMBIENTE) REFERENCES AMBIENTE_LAB(ID)
)



CREATE TABLE COMPUTADORAS(
	ID INT PRIMARY KEY NOT NULL,
	PROCESADOR VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(30) NOT NULL,
	ESTADO CHAR(1) CHECK (ESTADO IN('H','I','R'))
)

CREATE TABLE REG_COMPUTADORAS(
	ID INT PRIMARY KEY NOT NULL,
	ID_AMB_LABORATORIO INT NOT NULL,
	ID_COMPUTADORAS INT NOT NULL,
	ID_P_REG_ORDENADOR INT NOT NULL,
	FECHA_REG_C DATE NOT NULL,
	OBSERVACIONES VARCHAR(25),
	FOREIGN KEY (ID_AMB_LABORATORIO) REFERENCES AMBIENTE_LAB(ID),
	FOREIGN KEY (ID_COMPUTADORAS) REFERENCES COMPUTADORAS(ID),
	FOREIGN KEY (ID_P_REG_ORDENADOR) REFERENCES PERSONAL(ID)
)


CREATE TABLE FALLOS_DE_ORDENADOR (
ID INT PRIMARY KEY NOT NULL,
ID_ESTUDIANTE  INT NOT NULL,
ID_AMB_LAB  INT NOT NULL,
ID_COMPUTADORA  INT NOT NULL,
FECHA DATE NOT NULL,
DESCRIPCION VARCHAR(50),
FOREIGN KEY(ID_ESTUDIANTE)REFERENCES ESTUDIANTE(ID),
FOREIGN KEY(ID_COMPUTADORA)REFERENCES COMPUTADORAS(ID),
FOREIGN KEY(ID_AMB_LAB)REFERENCES AMBIENTE_LAB(ID)
)

CREATE TABLE PROGRAMAS(
	ID INT PRIMARY KEY NOT NULL,
	NOMBRE_PROG VARCHAR(30) NOT NULL,
	ID_PERSONAL_PROG INT NOT NULL,
	FECHA DATE NOT NULL,
	DESCRIPCION VARCHAR(30) NOT NULL,
	FOREIGN KEY (ID_PERSONAL_PROG) REFERENCES PERSONAL(ID),
)

CREATE TABLE IMPLEMENTA(
	ID INT PRIMARY KEY NOT NULL,
	ID_COMP INT NOT NULL,
	ID_PROG INT NOT NULL,
	FECHA DATE NOT NULL,
	ID_P_IM INT NOT NULL,
	FOREIGN KEY (ID_COMP) REFERENCES COMPUTADORAS(ID),
	FOREIGN KEY (ID_PROG) REFERENCES PROGRAMAS(ID),
	FOREIGN KEY (ID_P_IM) REFERENCES PERSONAL(ID)
 )

 CREATE TABLE UNIDAD_MANTENIMIENTO(
	ID INT PRIMARY KEY NOT NULL,
	ID_CARRERA INT NOT NULL,
	ID_PERSONAL INT NOT NULL,
	ID_AMB_UNI INT NOT NULL,
	DESCRIPCION VARCHAR(20),
	FECHA_MAN DATE,
	FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID),
	FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL(ID),
	FOREIGN KEY (ID_AMB_UNI) REFERENCES AMBIENTE_LAB(ID)
	
 )
 CREATE TABLE REPARACION(
 ID INT PRIMARY KEY NOT NULL,
 ID_ORDENADOR INT NOT NULL,
 ID_MANT INT NOT NULL,
 FECHA_REPARACION DATE,
 DESCRIPCION VARCHAR(40),
 FOREIGN KEY (ID_ORDENADOR)REFERENCES COMPUTADORAS(ID),
 FOREIGN KEY (ID_MANT)REFERENCES UNIDAD_MANTENIMIENTO(ID),
 
 )
 CREATE TABLE DOCENTES(
 ID INT PRIMARY KEY NOT NULL,
 NOMBRE VARCHAR(40),
 A_PATERNO VARCHAR(25)NOT NULL,
 A_MATERNO VARCHAR(25)NOT NULL,
 CI VARCHAR(11),
 DIRECCION VARCHAR(25)NOT NULL,
 TEL CHAR(7),
 CELULAR VARCHAR(8),
 CORREO VARCHAR(50),
 FECHA_NACIMIENTO DATE NOT NULL,
 ID_CONTRATO INT NOT NULL,
 GENERO CHAR(1) NOT NULL CHECK(GENERO IN('M' , 'V')),
 /*ID_PERSONAL INT () NOT NULL*/
 FOREIGN KEY (ID_CONTRATO)REFERENCES CONTRATO (ID)
  )





CREATE TABLE CRONOGRAMA
(
	ID INT PRIMARY KEY,
	ID_P_R_CRONOGRAMA INT NOT NULL,
	LUNES VARCHAR(12) CHECK(LUNES IN('HABILITADO','INHABILITADO','FERIADO')),
	MARTES VARCHAR(12) CHECK(MARTES IN('HABILITADO','INHABILITADO','FERIADO')),
	MIERCOLES VARCHAR(12) CHECK(MIERCOLES IN('HABILITADO','INHABILITADO','FERIADO')),
	JUEVES VARCHAR(12) CHECK(JUEVES IN('HABILITADO','INHABILITADO','FERIADO')),
	VIERNES VARCHAR(12) CHECK(VIERNES IN('HABILITADO','INHABILITADO','FERIADO')),
	SABADO VARCHAR(12) CHECK(SABADO IN('HABILITADO','INHABILITADO','FERIADO')),
	FOREIGN KEY(ID_P_R_CRONOGRAMA) REFERENCES PERSONAL(ID)
)


  CREATE TABLE HORARIO_DEFINIDO(
	ID INT PRIMARY KEY NOT NULL,
	ID_CRONOGRAMA INT NOT NULL,
	ID_P_H_DEF INT NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FIN TIME NOT NULL,
	ID_CRONO INT NOT NULL,
	FOREIGN KEY (ID_P_H_DEF) REFERENCES PERSONAL(ID),
	FOREIGN KEY (ID_CRONO) REFERENCES CRONOGRAMA(ID)
)

CREATE TABLE CLASES
(
	ID  INT PRIMARY KEY NOT NULL,
	ID_DOCENTE INT NOT NULL,
	ID_HORARIO_DEF INT NOT NULL,
	ID_AMB_LAB INT NOT NULL,
	ID_MATERIA INT NOT NULL,
	FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTES(ID),
	FOREIGN KEY(ID_HORARIO_DEF)REFERENCES HORARIO_DEFINIDO(ID),
	FOREIGN KEY(ID_AMB_LAB) REFERENCES AMBIENTE_LAB(ID),
	FOREIGN KEY(ID_MATERIA) REFERENCES MATERIA(ID)
)
CREATE TABLE ROL_U(
ID INT PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR(50),
PERMISOS  CHAR(3) NOT NULL CHECK (PERMISOS IN('ALL' , 'M', 'LOW'))
)

CREATE TABLE USUARIO
(
ID INT PRIMARY KEY NOT NULL,
ID_ROL INT NOT NULL,
NOMBRRE VARCHAR(12),
PASS VARCHAR(128),
FECHA_ACTUALIZACION DATE,
ESTADO BIT,
ID_PERSONAL INT NOT NULL,
FOREIGN KEY (ID_PERSONAL)REFERENCES PERSONAL(ID),
FOREIGN KEY (ID_ROL) REFERENCES ROL_U(ID)

)




CREATE TABLE ASIGNACION (
ID INT PRIMARY KEY NOT NULL,
ID_USUARIO INT NOT NULL,
ID_ESTUDIANTE  INT NOT NULL,
ID_DOCENTE  INT NOT NULL,
FECHA DATE NOT NULL,
OBSERVACION VARCHAR(50),
FOREIGN KEY(ID_USUARIO)REFERENCES USUARIO(ID),
FOREIGN KEY(ID_ESTUDIANTE)REFERENCES ESTUDIANTE(ID),
FOREIGN KEY(ID_DOCENTE)REFERENCES DOCENTES(ID)
)
SELECT * FROM DOCENTES
SELECT * FROM CONTRATO
SELECT * FROM PERSONAL

INSERT INTO DOCENTES VALUES(100,'JOAQUIN',NULL,'CASAS','6234567','AV BANDERAS #31','45784558','1245785','5/5/2022',)
INSERT INTO CONTRATO VALUES(10,'JOAQUIN',NULL,'CASAS','6234567','AV BANDERAS #31','45784558','1245785','5/5/2022',)
INSERT INTO PERSONAL VALUES(1,'JOAQUIN',NULL,'CASAS','6234567','45784558','1245785','AV BANDERAS #31','2525','5/5/2022','EN_LAB','M',1)





DROP TABLE USUARIO